# FUNDING.yml - Describes project funding options to display on sponsor buttons
# https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository
# https://help.github.com/en/articles/about-github-sponsors

github: [ syntaqx ]
issue_hunt: syntaqx
ko_fi: syntaqx
