version: '3.7'
services:

  mysql:
    image: mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: project
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432

volumes:
  mysql-data:
    driver: local
  postgres-data:
    driver: local
